- name: galaxyproject.postgresql
  version: 1.0.3
- name: galaxyproject.nginx
  version: 0.7.0
- name: natefoo.postgresql_objects
  version: 1.1
- name: galaxyproject.galaxy
  src: https://github.com/galaxyproject/ansible-galaxy.git
  version: c15de9f403c0a8a3702aa78d5d1959e9e6c8f6e5
- name: geerlingguy.pip
  version: 2.0.0
- src: uchida.miniconda
  version: 0.3.0
- src: usegalaxy_eu.certbot
  version: 0.1.5
